### ISSUE TITLE
'Market' values are not being read / saved / changed within the app.

### ISSUE THREAD

**Issue by Kopiernik** [giuinktse7/LapisItemEditor#4]
It is impossible to read / save / change anything in 'market' section for any item.
'Trade as' and 'Show as' seems to be not working at all, whenever I fill it with any id, its not saving it and showing the same id from my input on every item with 'market' option checked, but its never saving it to items.otb, if I dont edit anything it always shows unchecked 'Trade and Show as' with id 100, even for already existing items on the server.

**Comment by Kopiernik** [comment]
![image](https://github.com/giuinktse7/LapisItemEditor/assets/149948874/235f3fe3-25db-4cc0-8618-de01a63942d6)

**Comment by giuinktse7** [comment]
Correct, that is unfortunately not implemented yet. I made this tool with the main goal of generating OTBs for new clients and never got around to finishing the editing functionality.

I'll see if I can find the time to add it sometime soon, but if not I will happily accept a PR for it.

**Comment by giuinktse7** [comment]
This should be fixed in the [latest release](https://github.com/giuinktse7/LapisItemEditor/releases/tag/v0.2.0-alpha). Note however that the **items.otb file does not contain market information**. This information is stored in the `appearances.dat` file. You can save the modified `appearances.dat` by using the new button `Save client data`:

![image](https://github.com/giuinktse7/LapisItemEditor/assets/5380287/7c086dc9-94cc-4bf5-b6be-57af79288e8a)

Depending on your server you might need to update the `appearances.dat` for both the client and the server. I think TFS still uses `items.otb`, but e.g. [canary](https://github.com/opentibiabr/canary) uses `appearances.dat` instead (in `data/items`).
